# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-04 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='id',
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
