# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-04 03:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_auto_20180304_0302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weatherdetail',
            old_name='name',
            new_name='city',
        ),
    ]
