# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-04 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_auto_20180304_0306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weatherdetail',
            name='elevation',
        ),
        migrations.RemoveField(
            model_name='weatherdetail',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='weatherdetail',
            name='longitude',
        ),
        migrations.AddField(
            model_name='location',
            name='elevation',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=10, null=True),
        ),
    ]
